name: eShopOnWeb Build and Test

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  RESOURCE_GROUP: rgaz400eshoponweb21
  LOCATION: CentralUS
  TEMPLATE_FILE: infra/webapp.bicep
  SUBSCRIPTION_ID: 062bdd89-3a1b-49c4-87c4-472e4191c179
  WEBAPP_NAME: eshoponweb-webapp-Praphul1

jobs:
  buildandtest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        dotnet-quality: 'preview'

    - name: Restore dependencies
      run: dotnet restore ./eShopOnWeb.sln

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release

    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --c
